### ISSUE TITLE
Upload the latest version to npm

### ISSUE THREAD

**Issue by fjc0k** [jetiny/rollup-plugin-re#7]
steps:
1. open [https://unpkg.com/rollup-plugin-re/](https://unpkg.com/rollup-plugin-re/)
2. open `dist/rollup-plugin-re.cjs.js`
3. search `// test & replace`
4. you can not find the codes added by the PR: https://github.com/jetiny/rollup-plugin-re/pull/4

**Comment by jetiny** [comment]
+ rollup-plugin-re@1.0.7

**Comment by fjc0k** [comment]
@jetiny 老哥，稳
